version: 2
jobs: 
  build: 
    docker: 
      - image: cimg/node:20.10.0
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:KqIjQp8F0cZuLVjzCA/HbWxP49gSQ832/9c086wM6f8"
      - checkout
      - restore_cache:
          keys:
            - secretweb_nodemodules
      - run:
          name: Install
          command: pnpm install
      - save_cache:
          paths: 
            - node_modules
          key: secretweb_nodemodules
      - run:
          name: Build
          command: pnpm build
      - run: 
          name: Deploy
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy
          command: ./scripts/deploy.sh